import { strict as assert } from 'node:assert';
import { mkdtemp, mkdir, readFile, realpath, rm, symlink, writeFile, appendFile, access, rename } from 'node:fs/promises';
import { tmpdir } from 'node:os'; import { join, dirname } from 'node:path'; import { test } from 'node:test';
import { createNativeRetentionAdapter } from '../../../server/sessions/retention/provider.js';
import { DatabaseSync } from 'node:sqlite';
import { channel } from 'node:diagnostics_channel';
import { lstat } from 'node:fs/promises';
import type { RetentionRecord } from '../../../server/sessions/retention/policy.js';
import type { RetentionMember, RetentionManifest, RetentionOperationContext } from '../../../server/sessions/retention/types.js';
function record(filePath: string): RetentionRecord { return { kind:'subagent',session:{ id:'claude:child',nativeId:'child',provider:'claude',title:'fixture',cwd:'/',project:'fixture',status:'completed',statusReason:'fixture',createdAt:'2026-01-01T00:00:00Z',updatedAt:'2026-01-01T00:00:00Z',lastMessage:'done',messageCount:1,isSubagent:true,resumable:false,filePath,parentId:'claude:parent' } }; }
const candidate={rootId:'claude:child',ids:['claude:child'],reason:'child-expired' as const,revisions:{}};
const manifest:RetentionManifest={version:1,id:'fixture',createdAt:'2026-01-01T00:00:00Z',reason:'child-expired',sessions:[],files:[]};
async function fixture(){const temporary=await mkdtemp(join(tmpdir(),'tower-retention-provider-'));const base=await realpath(temporary);const root=join(base,'projects');await mkdir(root);const file=join(root,'child.jsonl');await writeFile(file,'fixture');const source=record(file);const parent=record(file);Object.assign(parent.session,{id:'claude:parent',nativeId:'parent',isSubagent:false,parentId:undefined,filePath:undefined});parent.kind='parent';let active=new Set<string>();let complete=true;const committed:RetentionMember[]=[];
 const context:RetentionOperationContext={operationId:'fixture-operation',journalMembers:()=>{const latest=new Map(committed.map(member=>[member.sessionId,member]));return structuredClone([...latest.values()]);},managedCold:()=>[],fresh:async()=>({now:Date.now(),migratedAt:0,complete,records:[source,parent],protectedIds:active}),commitMember:async member=>{committed.push(structuredClone(member));}};
 const adapter=createNativeRetentionAdapter({claude:[root],codex:[root]},{coldRoot:join(base,'cold'),codexHome:base,claudeHome:base,inspect:async()=>({complete,activeIds:active,issues:complete?[]:['denied']})});
 return {base,root,file,source,context,adapter,committed,active(value:Set<string>){active=value;},complete(value:boolean){complete=value;},close:()=>rm(temporary,{recursive:true,force:true})};}

test('Claude cold move and no-overwrite restore preserve original and exact sidecar',async()=>{const f=await fixture();try{await writeFile(f.file.replace('.jsonl','.meta.json'),'metadata');const lease=await f.adapter.reserve(candidate,[f.source],f.context);assert.ok(lease);await lease.preserveOwnership();const moved=await lease.moveCold();assert.equal(moved[0].state,'cold');assert.equal(f.committed[0].state,'intent');await assert.rejects(()=>access(f.file));assert.equal(await readFile(moved[0].coldPath!,'utf8'),'fixture');assert.equal((await lease.sources(moved)).length,2);const restored=await f.adapter.restore!(manifest,'restore-operation',moved,f.context);assert.equal(restored[0].state,'restored');assert.equal(await readFile(f.file,'utf8'),'fixture');assert.equal(await readFile(f.file.replace('.jsonl','.meta.json'),'utf8'),'metadata');await lease.release();}finally{await f.close();}});
test('active native parent and incomplete fresh inspection cannot cold move',async()=>{const f=await fixture();try{f.active(new Set(['claude:parent']));assert.equal(await f.adapter.reserve(candidate,[f.source],f.context),undefined);f.active(new Set());f.complete(false);await assert.rejects(()=>f.adapter.reserve(candidate,[f.source],f.context),/incomplete/);assert.equal(await readFile(f.file,'utf8'),'fixture');}finally{await f.close();}});
test('durable member intent failure leaves source untouched',async()=>{const f=await fixture();try{f.context.commitMember=async()=>{throw new Error('disk failed');};const lease=await f.adapter.reserve(candidate,[f.source],f.context);assert.ok(lease);await assert.rejects(()=>lease.moveCold(),/disk failed/);assert.equal(await readFile(f.file,'utf8'),'fixture');await lease.release();}finally{await f.close();}});
test('source recreation and late cold writing preserve both copies and expose conflict',async()=>{const f=await fixture();try{const lease=await f.adapter.reserve(candidate,[f.source],f.context);assert.ok(lease);const moved=await lease.moveCold();await appendFile(moved[0].coldPath!,' late writer');assert.equal((await f.adapter.inspectCold(moved)).members[0].state,'conflict');await writeFile(f.file,'new hot');const restored=await f.adapter.restore!(manifest,'restore-operation',moved,f.context);assert.equal(restored[0].state,'conflict');assert.equal(await readFile(f.file,'utf8'),'new hot');assert.equal(await readFile(moved[0].coldPath!,'utf8'),'fixture late writer');await lease.release();}finally{await f.close();}});
test('partial sidecar crash is recoverable without replacing an existing transcript',async()=>{const f=await fixture();try{await writeFile(f.file.replace('.jsonl','.meta.json'),'metadata');const lease=await f.adapter.reserve(candidate,[f.source],f.context);assert.ok(lease);const moved=await lease.moveCold();await rename(moved[0].coldPath!,f.file);const partial=await f.adapter.inspectCold(moved);assert.equal(partial.members[0].state,'conflict');const restored=await f.adapter.restore!(manifest,'restore-operation',partial.members,f.context);assert.equal(restored[0].state,'restored');assert.equal(await readFile(f.file.replace('.jsonl','.meta.json'),'utf8'),'metadata');await lease.release();}finally{await f.close();}});
test('read-only backup discovery validates roots, symlink ancestors and alias identity',async()=>{const f=await fixture();try{const alias=record(f.file);alias.session.id='claude:monitor-child';assert.deepEqual(await f.adapter.files([f.source,alias]),[{path:f.file,root:f.root,provider:'claude',nativeId:'child'}]);alias.session.nativeId='different';await assert.rejects(()=>f.adapter.files([f.source,alias]),/Conflicting transcript identity/);await assert.rejects(()=>f.adapter.files([record(join(f.base,'outside.jsonl'))]),/outside native roots/);await assert.rejects(()=>f.adapter.files([record('relative.jsonl')]),/absolute/);const outside=join(f.base,'outside');await mkdir(outside);await writeFile(join(outside,'child.jsonl'),'outside');await symlink(outside,join(f.root,'linked'));await assert.rejects(()=>f.adapter.files([record(join(f.root,'linked','child.jsonl'))]),/Unsafe transcript/);assert.equal(await readFile(f.file,'utf8'),'fixture');}finally{await f.close();}});
test('restore rejects forged native and cold paths without changing either original',async()=>{const f=await fixture();try{const lease=await f.adapter.reserve(candidate,[f.source],f.context);assert.ok(lease);const moved=await lease.moveCold();const outside=join(f.base,'outside.jsonl');await writeFile(outside,'outside');const bad={...moved[0],originalPath:outside};const restored=await f.adapter.restore!(manifest,'restore-operation',[bad],f.context);assert.equal(restored[0].state,'conflict');assert.equal(await readFile(outside,'utf8'),'outside');assert.equal(await readFile(moved[0].coldPath!,'utf8'),'fixture');const badCold={...moved[0],coldPath:outside};assert.equal((await f.adapter.restore!(manifest,'restore-operation',[badCold],f.context))[0].state,'conflict');assert.equal(await readFile(outside,'utf8'),'outside');await lease.release();}finally{await f.close();}});
test('late-writing cold inode remains available for an explicit no-overwrite restoration',async()=>{const f=await fixture();try{const lease=await f.adapter.reserve(candidate,[f.source],f.context);assert.ok(lease);const moved=await lease.moveCold();await appendFile(moved[0].coldPath!,' latest');const changed=(await f.adapter.inspectCold(moved)).members;assert.equal(changed[0].state,'conflict');const restored=await f.adapter.restore!(manifest,'restore-operation',changed,f.context);assert.equal(restored[0].state,'restored');assert.equal(await readFile(f.file,'utf8'),'fixture latest');await lease.release();}finally{await f.close();}});

test('native parent permits confirmed already-cold descendants but protects active, changed or conflicted descendants',async()=>{const f=await fixture();try{
 const home=join(f.base,'codex'),hot=join(home,'sessions'),archive=join(home,'archived_sessions');await mkdir(home);await mkdir(hot);await mkdir(archive);const parentPath=join(hot,'parent.jsonl'),childPath=join(archive,'child.jsonl');await writeFile(parentPath,'parent');await writeFile(childPath,'child');
 const db=new DatabaseSync(join(home,'state_5.sqlite'));db.exec('CREATE TABLE threads(id TEXT PRIMARY KEY,rollout_path TEXT,archived INTEGER); CREATE TABLE thread_spawn_edges(parent_thread_id TEXT,child_thread_id TEXT,status TEXT)');db.prepare('INSERT INTO threads VALUES (?,?,?)').run('parent',parentPath,0);db.prepare('INSERT INTO threads VALUES (?,?,?)').run('child',childPath,1);db.prepare('INSERT INTO thread_spawn_edges VALUES (?,?,?)').run('parent','child','closed');db.close();
 const info=await lstat(childPath);const cold:RetentionMember={sessionId:'codex:child',nativeId:'child',provider:'codex',parentId:'codex:parent',originalPath:join(hot,'child.jsonl'),coldPath:childPath,operationId:'old-operation',state:'cold',identity:{dev:Number(info.dev),ino:Number(info.ino),size:Number(info.size),mtimeMs:Number(info.mtimeMs)}};
 const parent=record(parentPath);parent.session.provider='codex';parent.session.id='codex:parent';parent.session.nativeId='parent';parent.session.parentId=undefined;parent.session.isSubagent=false;parent.kind='parent';let active=new Set<string>();
 const ctx:RetentionOperationContext={operationId:'new-operation',journalMembers:()=>[cold],managedCold:()=>[cold],fresh:async()=>({now:Date.now(),migratedAt:0,complete:true,records:[parent],protectedIds:new Set()}),commitMember:async()=>{}};
 const adapter=createNativeRetentionAdapter({claude:[f.root],codex:[hot,archive]},{codexHome:home,claudeHome:f.base,coldRoot:join(f.base,'cold'),inspect:async()=>({complete:true,activeIds:active,issues:[]})});const group={rootId:parent.session.id,ids:[parent.session.id],reason:'parent-limit' as const,revisions:{}};
 const lease=await adapter.reserve(group,[parent],ctx);assert.ok(lease);await lease.release();active=new Set(['codex:child']);assert.equal(await adapter.reserve(group,[parent],ctx),undefined);active=new Set();cold.state='conflict';assert.equal(await adapter.reserve(group,[parent],ctx),undefined);cold.state='cold';cold.parentId=undefined;assert.equal(await adapter.reserve(group,[parent],ctx),undefined);cold.parentId='codex:parent';await appendFile(childPath,' changed');assert.equal(await adapter.reserve(group,[parent],ctx),undefined);
 }finally{await f.close();}});

test('two thousand cold Codex records reuse one native metadata connection per reconciliation',async t=>{const f=await fixture();const opened=channel('tower.retention.codex-metadata-open');let count=0;const observed=()=>{count++;};try{
 const home=join(f.base,'codex'),hot=join(home,'sessions'),archive=join(home,'archived_sessions');await mkdir(home);await mkdir(hot);await mkdir(archive);const db=new DatabaseSync(join(home,'state_5.sqlite'));db.exec('CREATE TABLE threads(id TEXT PRIMARY KEY,rollout_path TEXT,archived INTEGER)');const insert=db.prepare('INSERT INTO threads VALUES (?,?,?)');const members:RetentionMember[]=[];
 for(let index=0;index<2000;index++){const id='fixture-'+index,path=join(archive,id+'.jsonl');await writeFile(path,'cold');const info=await lstat(path);insert.run(id,path,1);members.push({sessionId:'codex:'+id,nativeId:id,provider:'codex',originalPath:join(hot,id+'.jsonl'),coldPath:path,operationId:'old-operation',state:'cold',identity:{dev:Number(info.dev),ino:Number(info.ino),size:Number(info.size),mtimeMs:Number(info.mtimeMs)}});}db.close();
 const adapter=createNativeRetentionAdapter({claude:[f.root],codex:[hot,archive]},{codexHome:home,claudeHome:f.base,coldRoot:join(f.base,'cold'),inspect:async()=>({complete:true,activeIds:new Set(),issues:[]})});
 opened.subscribe(observed);const began=performance.now();const result=await adapter.inspectCold(members);const elapsed=performance.now()-began;opened.unsubscribe(observed);t.diagnostic(JSON.stringify({coldRecords:2000,metadataConnections:count,coldReconcileMs:Math.round(elapsed)}));assert.equal(result.complete,true);assert.equal(result.members.filter(member=>member.state==='cold').length,2000);assert.equal(count,1);
 count=0;await appendFile(members[777].coldPath!,' late write');opened.subscribe(observed);const changed=await adapter.inspectCold(members);opened.unsubscribe(observed);assert.equal(count,1);assert.equal(changed.complete,true);assert.equal(changed.members[777].state,'conflict');assert.equal(changed.members.filter(member=>member.state==='cold').length,1999);
 count=0;opened.subscribe(observed);const oversized=await adapter.inspectCold(Array.from({length:20001},()=>members[0]));opened.unsubscribe(observed);assert.equal(oversized.complete,false);assert.match(oversized.issues.join(';'),/budget/);assert.equal(count,0);assert.equal(oversized.members.length,20001);assert.equal(oversized.members[0].state,'cold');
 }finally{opened.unsubscribe(observed);await f.close();}});

test('partial sidecar ownership survives same-operation retry and full restoration', async () => {
 const f=await fixture();try{
  const meta=f.file.replace('.jsonl','.meta.json');await writeFile(meta,'metadata');
  const first=await f.adapter.reserve(candidate,[f.source],f.context);assert.ok(first);const moved=await first.moveCold();await first.release();
  await rename(moved[0].coldPath!,f.file);const partial=await f.adapter.inspectCold(moved);assert.equal(partial.members[0].state,'conflict');await f.context.commitMember(partial.members[0]);
  const retry=await f.adapter.reserve(candidate,[f.source],f.context);assert.ok(retry);const retried=await retry.moveCold();assert.equal(retried[0].state,'cold');assert.deepEqual(retried[0].sidecars,moved[0].sidecars);assert.equal((await retry.sources(retried)).length,2);
  const restored=await f.adapter.restore!(manifest,'restore-retry',retried,f.context);assert.equal(restored[0].state,'restored');assert.equal(await readFile(meta,'utf8'),'metadata');assert.equal(await readFile(f.file,'utf8'),'fixture');await assert.rejects(()=>access(moved[0].sidecars![0].coldPath));await retry.release();
 }finally{await f.close();}
});
test('foreign-operation partial ownership and changed cold metadata defer without losing either original', async()=>{
 const f=await fixture();try{
  const meta=f.file.replace('.jsonl','.meta.json');await writeFile(meta,'metadata');const first=await f.adapter.reserve(candidate,[f.source],f.context);assert.ok(first);const moved=await first.moveCold();await first.release();await rename(moved[0].coldPath!,f.file);await f.context.commitMember((await f.adapter.inspectCold(moved)).members[0]);
  const before=structuredClone(f.context.journalMembers());f.context.operationId='different-revision';assert.equal(await f.adapter.reserve(candidate,[f.source],f.context),undefined);assert.deepEqual(f.context.journalMembers(),before);
  f.context.operationId='fixture-operation';await appendFile(moved[0].sidecars![0].coldPath,' late-write');assert.equal(await f.adapter.reserve(candidate,[f.source],f.context),undefined);assert.deepEqual(f.context.journalMembers(),before);assert.equal(await readFile(f.file,'utf8'),'fixture');assert.equal(await readFile(moved[0].sidecars![0].coldPath,'utf8'),'metadata late-write');
 }finally{await f.close();}
});
test('partial retry preserves recreated hot metadata and completed restoration does not block a new operation',async()=>{
 const f=await fixture();try{
  const meta=f.file.replace('.jsonl','.meta.json');await writeFile(meta,'metadata');const first=await f.adapter.reserve(candidate,[f.source],f.context);assert.ok(first);const moved=await first.moveCold();await first.release();await rename(moved[0].coldPath!,f.file);await f.context.commitMember((await f.adapter.inspectCold(moved)).members[0]);
  const before=structuredClone(f.context.journalMembers());await writeFile(meta,'new hot metadata');assert.equal(await f.adapter.reserve(candidate,[f.source],f.context),undefined);assert.deepEqual(f.context.journalMembers(),before);assert.equal(await readFile(meta,'utf8'),'new hot metadata');assert.equal(await readFile(moved[0].sidecars![0].coldPath,'utf8'),'metadata');
 }finally{await f.close();}
 const restored=await fixture();try{
  const meta=restored.file.replace('.jsonl','.meta.json');await writeFile(meta,'metadata');const first=await restored.adapter.reserve(candidate,[restored.source],restored.context);assert.ok(first);const moved=await first.moveCold();await first.release();await restored.adapter.restore!(manifest,'restore-complete',moved,restored.context);
  restored.context.operationId='new-owner-after-restoration';const next=await restored.adapter.reserve(candidate,[restored.source],restored.context);assert.ok(next);assert.equal((await next.moveCold())[0].state,'cold');await next.release();
 }finally{await restored.close();}
});

test('cold ancestry keeps native-qualified live ancestors protected for archive and restore',async()=>{
 const f=await fixture();try{
  f.source.session.parentId='claude:bridge-alias';const fresh=f.context.fresh;
  f.context.fresh=async()=>{const base=await fresh();return {...base,records:base.records.map(item=>item.session.id==='claude:parent'?{...item,session:{...item.session,nativeId:'native-ancestor'}}:item),ancestry:[{id:'claude:bridge-alias',provider:'claude',nativeId:'bridge-native',parentId:'claude:parent',isSubagent:true}]};};
  for(const active of ['claude:native-ancestor','claude:bridge-native']){f.active(new Set([active]));assert.equal(await f.adapter.reserve(candidate,[f.source],f.context),undefined);}
  f.active(new Set());const lease=await f.adapter.reserve(candidate,[f.source],f.context);assert.ok(lease);const moved=await lease.moveCold();await lease.release();
  f.active(new Set(['claude:bridge-native']));const blocked=await f.adapter.restore!(manifest,'restore-active-bridge',moved,f.context);assert.equal(blocked[0].state,'conflict');await assert.rejects(()=>access(f.file));
  f.active(new Set());const restored=await f.adapter.restore!(manifest,'restore-inactive-bridge',moved,f.context);assert.equal(restored[0].state,'restored');assert.equal(await readFile(f.file,'utf8'),'fixture');
 }finally{await f.close();}
});
test('archive rejects unknown cold ancestry while restore tolerates unavailable ancestry roles',async()=>{
 const f=await fixture();try{
  const lease=await f.adapter.reserve(candidate,[f.source],f.context);assert.ok(lease);const moved=await lease.moveCold();await lease.release();
  const fresh=f.context.fresh;f.context.fresh=async()=>({...await fresh(),ancestry:[{id:'claude:parent',provider:'claude',nativeId:'parent'}],records:[f.source]});
  const restored=await f.adapter.restore!(manifest,'restore-unknown-role',moved,f.context);assert.equal(restored[0].state,'restored');assert.equal(await f.adapter.reserve(candidate,[f.source],f.context),undefined);
  f.context.fresh=async()=>({...await fresh(),records:[f.source]});assert.equal(await f.adapter.reserve(candidate,[f.source],f.context),undefined);
 }finally{await f.close();}
});
test('initial native member captures exact source role and verified direct child relations without retry grants',async()=>{
 const f=await fixture();try{
  f.source.session.parentLink='exec';const child=record(f.file);Object.assign(child.session,{id:'claude:descendant',nativeId:'descendant',parentId:f.source.session.id,parentLink:'exec'});const fresh=f.context.fresh;f.context.fresh=async()=>({...await fresh(),records:[...((await fresh()).records),child]});
  const lease=await f.adapter.reserve(candidate,[f.source],f.context);assert.ok(lease);const moved=await lease.moveCold();await lease.release();assert.equal(moved[0].isSubagent,true);assert.equal(moved[0].parentLink,'exec');assert.equal(moved[0].relationships?.[0].id,child.session.id);assert.equal(moved[0].relationships?.[0].parentId,f.source.session.id);
  await rename(moved[0].coldPath!,f.file);const legacy={...(await f.adapter.inspectCold(moved)).members[0]};delete legacy.isSubagent;delete legacy.parentLink;delete legacy.relationships;await f.context.commitMember(legacy);
  const retry=await f.adapter.reserve(candidate,[f.source],f.context);assert.ok(retry);const again=await retry.moveCold();assert.equal(again[0].isSubagent,undefined);assert.equal(again[0].parentLink,undefined);assert.equal(again[0].relationships,undefined);await retry.release();
 }finally{await f.close();}
});

test('cold ancestry cycles and resolved alias conflicts never grant archive or restoration',async()=>{
 const f=await fixture();try{
  const first=await f.adapter.reserve(candidate,[f.source],f.context);assert.ok(first);const moved=await first.moveCold();await first.release();const fresh=f.context.fresh;
  f.context.fresh=async()=>({...await fresh(),records:[f.source],ancestry:[{id:'claude:parent',provider:'claude',nativeId:'parent',isSubagent:true,parentId:f.source.session.id}]});
  assert.equal((await f.adapter.restore!(manifest,'restore-cycle',moved,f.context))[0].state,'conflict');
  f.context.fresh=async()=>({...await fresh(),blockedIds:new Set(['claude:parent'])});assert.equal((await f.adapter.restore!(manifest,'restore-alias-conflict',moved,f.context))[0].state,'conflict');await assert.rejects(()=>access(f.file));
 }finally{await f.close();}
});
test('one family reservation captures child relations from one shared fresh snapshot and still revalidates later',async()=>{
 const f=await fixture();try{
  const sources=[f.source];for(let index=1;index<128;index++){const path=join(f.root,'family-'+index+'.jsonl');await writeFile(path,'child');const child=record(path);Object.assign(child.session,{id:'claude:family-'+index,nativeId:'family-'+index,parentId:f.source.session.id});sources.push(child);}
  const fresh=f.context.fresh;let observations=0;f.context.fresh=async()=>{observations++;const base=await fresh();return {...base,records:[...base.records,...sources.slice(1)]};};
  const family={rootId:f.source.session.id,ids:sources.map(source=>source.session.id),reason:'explicit-archive' as const,revisions:{}};const lease=await f.adapter.reserve(family,sources,f.context);assert.ok(lease);assert.equal(observations,2);assert.equal(await lease.revalidate(),true);assert.equal(observations,3);
  f.active(new Set(['claude:parent']));assert.equal(await lease.revalidate(),false);assert.equal(observations,4);assert.equal(await readFile(f.file,'utf8'),'fixture');await lease.release();
 }finally{await f.close();}
});
