import { useSyncExternalStore } from 'react';
import { english } from './messages';

export type Language = 'ko' | 'en';
export const LANGUAGE_KEY = 'agent-session-tower.language';
type Values = Record<string | number, string | number>;
export function detectLanguage(saved: string | null, browserLanguage = ''): Language {
  if (saved === 'ko' || saved === 'en') return saved;
  return /^ko(?:-|$)/i.test(browserLanguage) ? 'ko' : 'en';
}
function initialLanguage(): Language {
  // A fixed server/test default is independent of the machine running the tests.
  if (typeof window === 'undefined') return 'ko';
  let saved: string | null = null;
  try { saved = window.localStorage.getItem(LANGUAGE_KEY); } catch { /* Private browsing can disable storage. */ }
  return detectLanguage(saved, window.navigator.language);
}
let language = initialLanguage();
const listeners = new Set<() => void>();
export const getLanguage = () => language;
export const locale = () => language === 'ko' ? 'ko-KR' : 'en-US';
export function translate(key: string, values: Values = {}, target: Language = language): string {
  return (target === 'en' ? english[key] ?? key : key).replace(/\{(\w+)\}/g, (match, name) => Object.hasOwn(values, name) ? String(values[name]) : match);
}
const sourceMessages = new Map(Object.entries(english).map(([ko, en]) => [en, ko]));
// Only errors generated by this application are eligible for interpolation matching.
// Captured file names, provider methods, and technical details remain verbatim.
const errorTemplates = [
  '{0}의 형식은 지원하지 않습니다.',
  '{0}의 라벨이 올바르지 않습니다.',
  '{0}의 문자열 제약은 지원하지 않습니다.',
  '{0}의 데이터 형식은 지원하지 않습니다.',
  '{0}의 선택지가 올바르지 않습니다.',
  '{0}의 선택지 라벨이 올바르지 않습니다.',
  '{0}의 숫자 제약은 지원하지 않습니다.',
  '{0}의 참/거짓 제약은 지원하지 않습니다.',
  '{0}의 목록 제약은 지원하지 않습니다.',
  '{0}의 목록 선택지는 지원하지 않습니다.',
  '{0}의 항목 유형은 지원하지 않습니다.',
  '예상하지 못한 양식 항목입니다: {0}.',
  '필수 항목에 답변하세요: {0}.',
  '{0}에 텍스트를 입력하세요.',
  '{0}의 길이가 허용 범위를 벗어났습니다.',
  '{1}에 허용 범위 내의 올바른 {0} 값을 입력하세요.',
  '{1}에 올바른 {0} 값을 입력하세요.',
  '{0}에 제시된 값을 선택하세요.',
  '{0}에 예 또는 아니요를 선택하세요.',
  '{0}에 올바른 목록 값을 선택하세요.',
  '파일은 최대 {0}개까지 첨부할 수 있습니다.',
  '{0}: 파일 하나는 {1} 이하여야 합니다.',
  '{0}: 이미지는 {1} 이하여야 합니다.',
  '첨부 파일의 전체 크기는 {0} 이하여야 합니다.',
  '{0}: 파일을 다시 첨부해 주세요.',
  '요청을 처리하지 못했습니다 ({0})',
  '폴더 그룹을 저장하지 못했습니다: {0}',
  '제목을 저장하지 못했습니다: {0}',
  '세션 표시 상태를 저장하지 못했습니다: {0}',
  '실패 기록을 지우지 못했습니다: {0}',
  'Codex {0} 응답을 확인하지 못했습니다. 요청을 다시 보내지 않았습니다. 원래 앱에서 확인하세요.',
  '요청 취소를 확인하지 못했습니다. {0}',
  '{0}에 연결할 수 없습니다.',
  '포트 {0}를 다른 프로그램이 쓰고 있습니다.',
  '원격 컴퓨터를 사용할 수 없습니다: {0}',
  '{0} 파일을 읽을 수 없어 원격 컴퓨터를 관리할 수 없습니다. 파일을 확인하거나 옮긴 뒤 Tower를 다시 시작하세요.',
  '{0} 파일을 읽을 수 없어 이 컴퓨터를 제어하는 컴퓨터를 관리할 수 없습니다. 파일을 확인하거나 옮긴 뒤 Tower를 다시 시작하세요.',
  'PATH에서 {0} CLI를 찾을 수 없습니다.',
  'PATH에서 {0} CLI를 더 이상 사용할 수 없습니다.',
  '새 세션을 만들려면 {0} CLI를 설치하고 PATH에 추가하세요.',
  '요청을 보내려면 {0} CLI를 설치하고 PATH에 추가하세요.',
  '요청은 {0}자 이하여야 합니다.',
  '작업 대기열을 저장할 수 없습니다: {0}',
  '{0} 권한이 거절되었습니다. 현재 권한으로 요청을 완료할 수 없습니다.',
  'Codex가 15초 안에 {0} 요청을 확인하지 않았습니다.',
  '{0} Codex가 요청을 받았을 수 있습니다. 자동으로 다시 보내지 않았습니다. 다시 시도하기 전에 원래 대화를 확인하세요.',
  'Codex가 요청한 상호작용({0})은 이 앱에서 지원하지 않습니다. 이 요청은 현재 모니터링 중인 턴에 속하지 않습니다.',
  'Codex가 요청한 상호작용({0})은 이 앱에서 지원하지 않습니다. 한 번만 허용하는 선택지와 지원되는 거절 선택지가 모두 제공되지 않았습니다. 원래 앱에서 요청을 확인하세요.',
  'Codex가 요청한 상호작용({0})은 이 앱에서 지원하지 않습니다. 검토할 명령어나 터미널 입력의 정확한 내용이 제공되지 않았습니다. 원래 앱에서 계속하세요.',
  'Codex가 요청한 상호작용({0})은 이 앱에서 지원하지 않습니다. 검토할 파일 변경 내용이 제공되지 않았습니다. 원래 앱에서 계속하세요.',
  'Codex가 요청한 상호작용({0})은 이 앱에서 지원하지 않습니다. 지원하지 않는 권한 범위가 요청되었습니다.',
  'Codex가 요청한 상호작용({0})은 이 앱에서 지원하지 않습니다. 이 상호작용은 원래 Codex 앱에서 계속하세요.',
  '{0}를 사용할 수 없습니다. 설치와 로그인을 확인하세요.',
  'Auto Prompt: {0} CLI를 찾을 수 없습니다. 먼저 해당 CLI를 설치하고 로그인하세요.',
  'Auto Prompt: Claude Code가 지원하지 않는 라우팅 이벤트를 반환했습니다 ({0}).',
  'Auto Prompt: {0} 라우팅이 정상적으로 종료되지 않았습니다. 해당 CLI의 로그인, 모델 접근 권한과 호환성을 확인하세요.',
].flatMap(key => [key, english[key]].map(template => {
  const names: string[] = [];
  const pattern = template.split(/(\{\w+\})/).map(part => {
    if (/^\{\w+\}$/.test(part)) { names.push(part.slice(1, -1)); return '([\\s\\S]+?)'; }
    return part.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  }).join('');
  return { key, names, expression: new RegExp(`^${pattern}$`) };
}));
/** Only known application messages are localized; native provider output stays verbatim. */
export function translateMessage(message: string): string {
  if (!message) return message;
  if (Object.hasOwn(english, message)) return translate(message);
  const key = sourceMessages.get(message);
  if (key !== undefined) return translate(key);
  for (const template of errorTemplates) {
    const match = template.expression.exec(message);
    if (match) return translate(template.key, Object.fromEntries(template.names.map((name, index) => [name, match[index + 1]])));
  }
  return message;
}
export function setLanguage(next: Language) {
  if (next !== 'ko' && next !== 'en') return;
  language = next;
  if (typeof document !== 'undefined') document.documentElement.lang = next;
  if (typeof window !== 'undefined') {
    try { window.localStorage.setItem(LANGUAGE_KEY, next); } catch { /* Keep the language for this visit. */ }
  }
  listeners.forEach(listener => listener());
}
function subscribe(listener: () => void) { listeners.add(listener); return () => { listeners.delete(listener); }; }
export function useI18n() {
  const language = useSyncExternalStore(subscribe, getLanguage, getLanguage);
  return { language, t: translate, setLanguage };
}
